import type { Listing } from "@/types";

// Realistic Belgian property mock data
export const MOCK_LISTINGS: Omit<Listing, "createdAt" | "firstSeenAt" | "lastSeenAt">[] = [
  {
    id: "lst_001",
    source: "mock",
    sourceUrl: null,
    title: "Charming terraced house with garden in Ixelles",
    propertyType: "house",
    transactionType: "sale",
    askingPrice: 695000,
    municipality: "Ixelles",
    postalCode: "1050",
    province: "Brussels-Capital",
    latitude: 50.8279,
    longitude: 4.3695,
    bedrooms: 3,
    bathrooms: 2,
    livingAreaM2: 185,
    landAreaM2: 95,
    epcScore: 280,
    energyLabel: "D",
    condition: "good",
    constructionYear: 1920,
    floor: null,
    hasTerrace: false,
    hasGarden: true,
    hasParking: false,
    hasElevator: false,
    description: "Beautiful terraced house in a quiet street near Place Flagey. 3 bedrooms, renovated kitchen, sunny garden. Close to shops and transport.",
    photoUrls: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
    ],
    isActive: true,
    isApproved: true,
  },
  {
    id: "lst_002",
    source: "mock",
    sourceUrl: null,
    title: "Modern apartment with terrace in Antwerp Zuid",
    propertyType: "apartment",
    transactionType: "sale",
    askingPrice: 349000,
    municipality: "Antwerpen",
    postalCode: "2000",
    province: "Antwerp",
    latitude: 51.2056,
    longitude: 4.3944,
    bedrooms: 2,
    bathrooms: 1,
    livingAreaM2: 95,
    landAreaM2: null,
    epcScore: 150,
    energyLabel: "B",
    condition: "as new",
    constructionYear: 2019,
    floor: 4,
    hasTerrace: true,
    hasGarden: false,
    hasParking: true,
    hasElevator: true,
    description: "Stunning 2-bedroom apartment in the trendy Zuid district. Open plan living with high-end finishes, large terrace with city views. Underground parking included.",
    photoUrls: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
    ],
    isActive: true,
    isApproved: true,
  },
  {
    id: "lst_003",
    source: "mock",
    sourceUrl: null,
    title: "Spacious family villa in Waterloo",
    propertyType: "house",
    transactionType: "sale",
    askingPrice: 875000,
    municipality: "Waterloo",
    postalCode: "1410",
    province: "Walloon Brabant",
    latitude: 50.7147,
    longitude: 4.3830,
    bedrooms: 5,
    bathrooms: 3,
    livingAreaM2: 320,
    landAreaM2: 800,
    epcScore: 320,
    energyLabel: "E",
    condition: "good",
    constructionYear: 1985,
    floor: null,
    hasTerrace: true,
    hasGarden: true,
    hasParking: true,
    hasElevator: false,
    description: "Impressive family villa on a generous plot in prestigious Waterloo. 5 bedrooms, 3 bathrooms, double garage, landscaped garden with pool potential.",
    photoUrls: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
    ],
    isActive: true,
    isApproved: true,
  },
  {
    id: "lst_004",
    source: "mock",
    sourceUrl: null,
    title: "Cozy studio near Ghent city center",
    propertyType: "apartment",
    transactionType: "sale",
    askingPrice: 165000,
    municipality: "Gent",
    postalCode: "9000",
    province: "East Flanders",
    latitude: 51.0543,
    longitude: 3.7174,
    bedrooms: 1,
    bathrooms: 1,
    livingAreaM2: 42,
    landAreaM2: null,
    epcScore: 200,
    energyLabel: "C",
    condition: "good",
    constructionYear: 2005,
    floor: 2,
    hasTerrace: false,
    hasGarden: false,
    hasParking: false,
    hasElevator: true,
    description: "Well-maintained studio apartment ideal for students or investors. Walking distance to Ghent University and Sint-Pieters station.",
    photoUrls: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&h=600&fit=crop",
    ],
    isActive: true,
    isApproved: true,
  },
  {
    id: "lst_005",
    source: "mock",
    sourceUrl: null,
    title: "Renovated bel-étage in Schaerbeek",
    propertyType: "house",
    transactionType: "sale",
    askingPrice: 525000,
    municipality: "Schaerbeek",
    postalCode: "1030",
    province: "Brussels-Capital",
    latitude: 50.8666,
    longitude: 4.3791,
    bedrooms: 4,
    bathrooms: 2,
    livingAreaM2: 210,
    landAreaM2: 120,
    epcScore: 180,
    energyLabel: "C",
    condition: "renovated",
    constructionYear: 1900,
    floor: null,
    hasTerrace: false,
    hasGarden: true,
    hasParking: false,
    hasElevator: false,
    description: "Beautifully renovated bel-étage with original Art Nouveau details. 4 bedrooms, modern kitchen, cellar, south-facing garden. Near Josaphat Park.",
    photoUrls: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&h=600&fit=crop",
    ],
    isActive: true,
    isApproved: true,
  },
  {
    id: "lst_006",
    source: "mock",
    sourceUrl: null,
    title: "Penthouse with panoramic view in Liège",
    propertyType: "apartment",
    transactionType: "sale",
    askingPrice: 285000,
    municipality: "Liège",
    postalCode: "4000",
    province: "Liège",
    latitude: 50.6326,
    longitude: 5.5797,
    bedrooms: 2,
    bathrooms: 1,
    livingAreaM2: 110,
    landAreaM2: null,
    epcScore: 160,
    energyLabel: "B",
    condition: "as new",
    constructionYear: 2021,
    floor: 8,
    hasTerrace: true,
    hasGarden: false,
    hasParking: true,
    hasElevator: true,
    description: "Top-floor penthouse with wrap-around terrace and stunning Meuse valley views. High-end finishes, underfloor heating, underground parking.",
    photoUrls: [
      "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=600&fit=crop",
    ],
    isActive: true,
    isApproved: true,
  },
  {
    id: "lst_007",
    source: "mock",
    sourceUrl: null,
    title: "Starter home in Charleroi suburb",
    propertyType: "house",
    transactionType: "sale",
    askingPrice: 145000,
    municipality: "Marchienne-au-Pont",
    postalCode: "6030",
    province: "Hainaut",
    latitude: 50.4056,
    longitude: 4.3986,
    bedrooms: 3,
    bathrooms: 1,
    livingAreaM2: 120,
    landAreaM2: 180,
    epcScore: 450,
    energyLabel: "F",
    condition: "to renovate",
    constructionYear: 1950,
    floor: null,
    hasTerrace: false,
    hasGarden: true,
    hasParking: true,
    hasElevator: false,
    description: "Affordable 3-bedroom house with renovation potential. Large garden, garage, quiet residential area. Perfect for first-time buyers with a vision.",
    photoUrls: [
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600585153490-76fb20a32601?w=800&h=600&fit=crop",
    ],
    isActive: true,
    isApproved: true,
  },
  {
    id: "lst_008",
    source: "mock",
    sourceUrl: null,
    title: "Bright apartment near Bruges market square",
    propertyType: "apartment",
    transactionType: "sale",
    askingPrice: 275000,
    municipality: "Brugge",
    postalCode: "8000",
    province: "West Flanders",
    latitude: 51.2093,
    longitude: 3.2247,
    bedrooms: 2,
    bathrooms: 1,
    livingAreaM2: 85,
    landAreaM2: null,
    epcScore: 250,
    energyLabel: "D",
    condition: "good",
    constructionYear: 1998,
    floor: 3,
    hasTerrace: true,
    hasGarden: false,
    hasParking: false,
    hasElevator: true,
    description: "Charming apartment in the heart of historic Bruges. 2 bedrooms, open kitchen, terrace with canal views. Walking distance to everything.",
    photoUrls: [
      "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&h=600&fit=crop",
    ],
    isActive: true,
    isApproved: true,
  },
  {
    id: "lst_009",
    source: "mock",
    sourceUrl: null,
    title: "Contemporary villa in Knokke",
    propertyType: "house",
    transactionType: "sale",
    askingPrice: 1450000,
    municipality: "Knokke-Heist",
    postalCode: "8300",
    province: "West Flanders",
    latitude: 51.3530,
    longitude: 3.2920,
    bedrooms: 4,
    bathrooms: 3,
    livingAreaM2: 280,
    landAreaM2: 450,
    epcScore: 90,
    energyLabel: "A",
    condition: "as new",
    constructionYear: 2022,
    floor: null,
    hasTerrace: true,
    hasGarden: true,
    hasParking: true,
    hasElevator: false,
    description: "Architect-designed villa minutes from the beach. Open floor plan, premium materials, heated pool, landscaped garden. The ultimate coastal lifestyle.",
    photoUrls: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    ],
    isActive: true,
    isApproved: true,
  },
  {
    id: "lst_010",
    source: "mock",
    sourceUrl: null,
    title: "Investment apartment in Leuven student quarter",
    propertyType: "apartment",
    transactionType: "sale",
    askingPrice: 215000,
    municipality: "Leuven",
    postalCode: "3000",
    province: "Flemish Brabant",
    latitude: 50.8798,
    longitude: 4.7005,
    bedrooms: 1,
    bathrooms: 1,
    livingAreaM2: 55,
    landAreaM2: null,
    epcScore: 210,
    energyLabel: "C",
    condition: "good",
    constructionYear: 2010,
    floor: 1,
    hasTerrace: true,
    hasGarden: false,
    hasParking: true,
    hasElevator: true,
    description: "Well-located 1-bedroom apartment near KU Leuven campus. Currently rented at €750/month. Ideal investment property with strong rental yield.",
    photoUrls: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
    ],
    isActive: true,
    isApproved: true,
  },
  {
    id: "lst_011",
    source: "mock",
    sourceUrl: null,
    title: "Art Deco apartment in Elsene/Ixelles",
    propertyType: "apartment",
    transactionType: "sale",
    askingPrice: 425000,
    municipality: "Ixelles",
    postalCode: "1050",
    province: "Brussels-Capital",
    latitude: 50.8265,
    longitude: 4.3710,
    bedrooms: 3,
    bathrooms: 1,
    livingAreaM2: 130,
    landAreaM2: null,
    epcScore: 310,
    energyLabel: "E",
    condition: "good",
    constructionYear: 1935,
    floor: 2,
    hasTerrace: false,
    hasGarden: false,
    hasParking: false,
    hasElevator: false,
    description: "Elegant Art Deco apartment with original parquet, high ceilings, and stained glass. 3 spacious bedrooms near Avenue Louise. Character meets location.",
    photoUrls: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
    ],
    isActive: true,
    isApproved: true,
  },
  {
    id: "lst_012",
    source: "mock",
    sourceUrl: null,
    title: "Farmhouse conversion in Ardennes",
    propertyType: "house",
    transactionType: "sale",
    askingPrice: 320000,
    municipality: "Durbuy",
    postalCode: "6940",
    province: "Luxembourg",
    latitude: 50.3527,
    longitude: 5.4564,
    bedrooms: 4,
    bathrooms: 2,
    livingAreaM2: 240,
    landAreaM2: 2500,
    epcScore: 380,
    energyLabel: "E",
    condition: "good",
    constructionYear: 1850,
    floor: null,
    hasTerrace: true,
    hasGarden: true,
    hasParking: true,
    hasElevator: false,
    description: "Beautifully converted stone farmhouse in the heart of the Ardennes. Exposed beams, wood-burning stove, large garden with orchard. Perfect countryside retreat.",
    photoUrls: [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600585153490-76fb20a32601?w=800&h=600&fit=crop",
    ],
    isActive: true,
    isApproved: true,
  },
  {
    id: "lst_013",
    source: "mock",
    sourceUrl: null,
    title: "New-build apartment in Namur center",
    propertyType: "apartment",
    transactionType: "sale",
    askingPrice: 235000,
    municipality: "Namur",
    postalCode: "5000",
    province: "Namur",
    latitude: 50.4674,
    longitude: 4.8720,
    bedrooms: 2,
    bathrooms: 1,
    livingAreaM2: 78,
    landAreaM2: null,
    epcScore: 80,
    energyLabel: "A",
    condition: "as new",
    constructionYear: 2023,
    floor: 3,
    hasTerrace: true,
    hasGarden: false,
    hasParking: true,
    hasElevator: true,
    description: "Brand new 2-bedroom apartment in Namur city center. Triple glazing, heat pump, large terrace. Low energy costs guaranteed. Move-in ready.",
    photoUrls: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800&h=600&fit=crop",
    ],
    isActive: true,
    isApproved: true,
  },
  {
    id: "lst_014",
    source: "mock",
    sourceUrl: null,
    title: "Row house with potential in Molenbeek",
    propertyType: "house",
    transactionType: "sale",
    askingPrice: 295000,
    municipality: "Molenbeek-Saint-Jean",
    postalCode: "1080",
    province: "Brussels-Capital",
    latitude: 50.8556,
    longitude: 4.3295,
    bedrooms: 3,
    bathrooms: 1,
    livingAreaM2: 150,
    landAreaM2: 60,
    epcScore: 420,
    energyLabel: "F",
    condition: "to renovate",
    constructionYear: 1910,
    floor: null,
    hasTerrace: false,
    hasGarden: true,
    hasParking: false,
    hasElevator: false,
    description: "Spacious row house in up-and-coming area near the canal. Needs full renovation but offers great volume. Close to metro and Dansaert area.",
    photoUrls: [
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    ],
    isActive: true,
    isApproved: true,
  },
  {
    id: "lst_015",
    source: "mock",
    sourceUrl: null,
    title: "Luxury flat in Woluwe-Saint-Pierre",
    propertyType: "apartment",
    transactionType: "sale",
    askingPrice: 550000,
    municipality: "Woluwe-Saint-Pierre",
    postalCode: "1150",
    province: "Brussels-Capital",
    latitude: 50.8342,
    longitude: 4.4252,
    bedrooms: 3,
    bathrooms: 2,
    livingAreaM2: 150,
    landAreaM2: null,
    epcScore: 170,
    energyLabel: "B",
    condition: "renovated",
    constructionYear: 1975,
    floor: 5,
    hasTerrace: true,
    hasGarden: false,
    hasParking: true,
    hasElevator: true,
    description: "Luxuriously renovated apartment in green Woluwe. 3 bedrooms, 2 bathrooms, south-facing terrace, double parking. Near Woluwe Park and international schools.",
    photoUrls: [
      "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
    ],
    isActive: true,
    isApproved: true,
  },
];
